# Generated by Django 5.0.3 on 2024-04-15 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_remove_customuser_full_name_remove_customuser_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=254)),
                ('bio', models.TextField(blank=True, max_length=1000)),
                ('location', models.CharField(max_length=100)),
                ('birth_date', models.DateField(null=True)),
                ('links', models.TextField(blank=True, max_length=1000)),
                ('avatar', models.ImageField(default='avatars/default_avatar.png', upload_to='avatars/')),
            ],
        ),
    ]
