# Generated by Django 5.0.3 on 2024-04-16 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userslinks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='links',
        ),
    ]
